spring:
  profiles.active: local
  redis:
    host: ${vcap.services.p-redis.credentials.host:redis}
    port: ${vcap.services.p-redis.credentials.port:6379}
    password: ${vcap.services.p-redis.credentials.password:guest}
server:
  port: 9000
security:
  basic:
    enabled: false
management:
  context-path: /manage
  security:
    enabled: false
endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex
logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: DEBUG
    io.pivotal.sfdc: DEBUG

ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:authservice}
    preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.p-service-registry.credentials.uri:http://discovery:8761}/eureka/

sfdc:
  client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
  client_key: 4631320832041516337
  uid: jigsheth@sfdc.com
  pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3

---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    nonSecurePort: ${server.port}

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: ${spring.application.name}
