spring:
  profiles.active: local
server:
  port: 9000
security:
  basic:
    enabled: false
management:
  context-path: /manage
  security:
    enabled: false
endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex
logging:
  level:
    io.pivotal.sfdc: INFO
eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5

sfdc:
  client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
  client_key: 4631320832041516337
  uid: jigsheth@sfdc.com
  pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3

---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: ${spring.application.name}
